
spring.application.name=melody-generator

spring.datasource.url=jdbc:postgresql://localhost:5432/melody_generator
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

jwt.secret=${JWT_SECRET}
app.jwt.expires-in=3600

spring.jpa.hibernate.ddl-auto=update